version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    working_directory: ~/yamlette
    steps:
      - checkout
      - run: rustc -vV
      - run: cargo -vV
      - run: cargo build --verbose

  reader:
    docker:
      - image: circleci/rust:latest
    working_directory: ~/yamlette
    steps:
      - checkout
      - run: rustc -vV
      - run: cargo -vV
      - run: cargo test --jobs=1 --test-threads=1 --verbose --features test_reader

  savant:
    docker:
      - image: circleci/rust:latest
    working_directory: ~/yamlette
    steps:
      - checkout
      - run: rustc -vV
      - run: cargo -vV
      - run: cargo test --jobs=1 --test-threads=1 --verbose --features test_savant

  sage:
    docker:
      - image: circleci/rust:latest
    working_directory: ~/yamlette
    steps:
      - checkout
      - run: rustc -vV
      - run: cargo -vV
      - run: cargo test --jobs=1 --test-threads=1 --verbose --features test_sage

  book:
    docker:
      - image: circleci/rust:latest
    working_directory: ~/yamlette
    steps:
      - checkout
      - run: rustc -vV
      - run: cargo -vV
      - run: cargo test --jobs=1 --test-threads=1 --verbose --features test_book

  orchestra:
    docker:
      - image: circleci/rust:latest
    working_directory: ~/yamlette
    steps:
      - checkout
      - run: rustc -vV
      - run: cargo -vV
      - run: cargo test --jobs=1 --test-threads=1 --verbose --features test_orchestra

  face:
    docker:
      - image: circleci/rust:latest
    working_directory: ~/yamlette
    steps:
      - checkout
      - run: rustc -vV
      - run: cargo -vV
      - run: cargo test --jobs=1 --test-threads=1 --verbose --features test_face

workflows:
  version: 2
  build:
    jobs:
      - build

      - reader:
          requires:
            - build

      - savant:
          requires:
            - build

      - sage:
          requires:
            - build

      - book:
          requires:
            - build

      - orchestra:
          requires:
            - build


      - face:
          requires:
            - build
