version: 2
jobs:
  build:
    machine: true

    working_directory: ~/yamlette

    steps:
      - run: apt-get -qq update; apt-get -y install git curl gcc
      - checkout
      - run: git submodule sync && git submodule update --init

      - run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y

      - run: rustc -vV
      - run: cargo -vV
      - run: cargo build --verbose
      - run: time cargo test --features onetest
