version: 2
jobs:
  build:
    machine: true

    working_directory: ~/yamlette

    steps:
      - run: sudo apt-get -qq update && sudo apt-get -y install git curl gcc
      - checkout
      - run: git submodule sync && git submodule update --init

      - run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
      - run: echo 'export PATH="$PATH:$HOME/.cargo/bin"' >> ~/.bashrc

      - run: rustc -vV
      - run: cargo -vV
      - run: cargo build --verbose
      - run: cargo test --features onetest
