version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest

    working_directory: ~/yamlette

    steps:
      - checkout

      - run: rustc -vV
      - run: cargo -vV
      - run: cargo build --verbose
      - run: cargo test -- --jobs=1 --test-threads=1 --verbose --features test_reader
      - run: cargo test -- --jobs=1 --test-threads=1 --verbose --features test_savant
      - run: cargo test -- --jobs=1 --test-threads=1 --verbose --features test_sage
      - run: cargo test -- --jobs=1 --test-threads=1 --verbose --features test_book
      - run: cargo test -- --jobs=1 --test-threads=1 --verbose --features test_orchestra
      - run: cargo test -- --jobs=1 --test-threads=1 --verbose --features test_face
