on: [push, pull_request]

name: Main CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test "test_reader"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --features test_reader

      - name: Run cargo test "test_savant"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --features test_savant

      - name: Run cargo test "test_sage"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --features test_sage

      - name: Run cargo test "test_book"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --features test_book

      - name: Run cargo test "test_orchestra"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --features test_orchestra

      - name: Run cargo test "test_face"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --features test_face

  # lints:
  #   name: Lints
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@v2

  #     - name: Install stable toolchain
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         profile: minimal
  #         toolchain: stable
  #         override: true
  #         components: rustfmt, clippy

  #     - name: Run cargo fmt
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: fmt
  #         args: --all -- --check

  #     - name: Run cargo clippy
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: clippy
  #         args: --all-features -- -D warnings